defaults:
  defaults: &defaults
    working_directory: '/go/src/github.com/influxdata/telegraf'
    environment:
      GOFLAGS: -p=8
  go-1_13: &go-1_13
    docker:
      - image: 'quay.io/influxdb/telegraf-ci:1.13.8'

version: 2
jobs:
  deps:
    <<: [ *defaults, *go-1_13 ]
    steps:
      - checkout
      - restore_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
      - run: 'make deps'
      - run: 'make tidy'
      - save_cache:
          name: 'go module cache'
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - '/go/pkg/mod'
      - persist_to_workspace:
          root: '/go'
          paths:
            - '*'

  test-go-1.13:
    <<: [ *defaults, *go-1_13 ]
    steps:
      - attach_workspace:
          at: '/go'
      - run: 'make'
      - run: 'make check'
      - run: 'make check-deps'
      - run: 'make test'

workflows:
  version: 2
  check:
    jobs:
      - 'deps'
      - 'test-go-1.13':
          requires:
            - 'deps'
